Fix gcc type error with wxEmptyString
Compiling with gcc 6.3.0 gave the following error
wxQuincy.h:93:95: error: operands to ?: have
different types ‘const wxString’ and ‘const wxChar* {aka const
wchar_t*}’

This is caused by wxEmptyString being of type const wxChar*
Fixed the problem by substituting wxT("") which is actually a wxString